#-- copyright
# OpenProject is a project management system.
# Copyright (C) 2012-2018 the OpenProject Foundation (OPF)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License version 3.
#
# OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
# Copyright (C) 2006-2018 Jean-Philippe Lang
# Copyright (C) 2010-2013 the ChiliProject Team
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# See doc/COPYRIGHT.rdoc for more details.
#++


###################################
#
# This file was generated by
# openproject-devkit.
#
# Do not modify this file directly!
#
###################################

language: ruby

rvm:
  - 2.5.1

sudo: required
dist: trusty

cache:
  bundler: true
  directories:
    - frontend/node_modules

branches:
  only:
    - master
    - dev
    - /^(stable|release)\/.*$/

env:
  global:
    - CI=true
    - RAILS_ENV=test

  matrix:
    - "TEST_SUITE=npm DB=none"


    - "TEST_SUITE=spec_legacy       DB=mysql     GROUP_SIZE=1 GROUP=1"
    - "TEST_SUITE=spec_legacy       DB=postgres  GROUP_SIZE=1 GROUP=1"

    - "TEST_SUITE=cucumber       DB=mysql     GROUP_SIZE=1 GROUP=1"
    - "TEST_SUITE=cucumber       DB=postgres  GROUP_SIZE=1 GROUP=1"

    - "TEST_SUITE=specs       DB=mysql     GROUP_SIZE=4 GROUP=1"
    - "TEST_SUITE=specs       DB=postgres  GROUP_SIZE=4 GROUP=1"
    - "TEST_SUITE=specs       DB=mysql     GROUP_SIZE=4 GROUP=2"
    - "TEST_SUITE=specs       DB=postgres  GROUP_SIZE=4 GROUP=2"
    - "TEST_SUITE=specs       DB=mysql     GROUP_SIZE=4 GROUP=3"
    - "TEST_SUITE=specs       DB=postgres  GROUP_SIZE=4 GROUP=3"
    - "TEST_SUITE=specs       DB=mysql     GROUP_SIZE=4 GROUP=4"
    - "TEST_SUITE=specs       DB=postgres  GROUP_SIZE=4 GROUP=4"

    - "TEST_SUITE=features       DB=mysql     GROUP_SIZE=4 GROUP=1"
    - "TEST_SUITE=features       DB=postgres  GROUP_SIZE=4 GROUP=1"
    - "TEST_SUITE=features       DB=mysql     GROUP_SIZE=4 GROUP=2"
    - "TEST_SUITE=features       DB=postgres  GROUP_SIZE=4 GROUP=2"
    - "TEST_SUITE=features       DB=mysql     GROUP_SIZE=4 GROUP=3"
    - "TEST_SUITE=features       DB=postgres  GROUP_SIZE=4 GROUP=3"
    - "TEST_SUITE=features       DB=mysql     GROUP_SIZE=4 GROUP=4"
    - "TEST_SUITE=features       DB=postgres  GROUP_SIZE=4 GROUP=4"

    - "TEST_SUITE=plugins:specs       DB=mysql     GROUP_SIZE=1 GROUP=1"
    - "TEST_SUITE=plugins:specs       DB=postgres  GROUP_SIZE=1 GROUP=1"

    - "TEST_SUITE=plugins:features       DB=mysql     GROUP_SIZE=1 GROUP=1"
    - "TEST_SUITE=plugins:features       DB=postgres  GROUP_SIZE=1 GROUP=1"

    - "TEST_SUITE=plugins:cucumber       DB=mysql     GROUP_SIZE=1 GROUP=1"
    - "TEST_SUITE=plugins:cucumber       DB=postgres  GROUP_SIZE=1 GROUP=1"


before_install:

  # Install pandoc for testing textile migration
  - travis_retry sudo apt-get update -qq
  - travis_retry sudo apt-get install -qq pandoc

  # Install Node latest LTS
  - "nvm install --lts"
  # work around https://github.com/travis-ci/travis-ci/issues/8969
  - travis_retry gem update --system
  # Don't install 1.16.3
  - gem install bundler -v 1.16.2


bundler_args: --binstubs --without development production docker

before_script:
  - bash script/ci_setup.sh $TEST_SUITE $DB

script:
  - bash script/ci_runner.sh

notifications:
  email: false
  slack:
    on_success: change
    on_failure: always
    on_pull_requests: false
    rooms:
      - secure: DzTFQBORAgS6ncPWuP6j60rDyHq/Fw4STPPi8CyQCbpNnqJKtbznJJqZH5JQMHAHE7ak2awnGwK3x4Ls0SmSUOxxKn1r3LGNP6INdvHbf7YG7Vk247+uau4xOx/JDS0ueb9VwYyHvD8TM9Jh1BYaPvCmvTh9WBWCnlWFteAyGT8cpAtMtVRK/GFS4QWukG/uBo/lWI/Lw4DU5jPZonj/mW9XconT3qCqHsRZ8LgIF/3zOzO2b6N9R2mbyHmOqO+X36XsFL5lrfH5A7Z9ZZ5UZNqzvhjf/Ft2NLLv9RVQMleFlGEavCcr5sCXQRrb6ffmKKJoVilopvmpuWaVRkVqx8Wl6qCjXUefeiHXCM6+HWFO9I+xvh59e/Dl4mPASCQOamOuNjAva2JgpxP1aifDvt2jdAjPagf2Ss5csRsR2pq5VR/eyDu8U03hZSzphDqSgCqxRJtBv50V7KByTFO6u3AefYw71EZYX6khKFCZZDQ+GAZLdZGvhZXzecejMJETTz+f8m8Nd+M+uidCnND+vDKoZDxI8lSDE7zYdJovpf2M2vUQbBUgKtKOfoY22YqG3O77/HhrVrS8hoJAfdE/wSGYktYQre90VWkekBiU57/PXqSU2hnRFGytWonfNi1M89Ib5F4Vsr/AuBvXx2//PkOpiZwJFC/LT9d394Ls3Mo=

addons:
  chrome: stable
  postgresql: "9.6"
